apiVersion: apps/v1
kind: Deployment
metadata:
  name: subalarm
  namespace: boat

spec:
  replicas: 1

  selector:
    matchLabels:
      app: subalarm

  template:
    metadata:
      labels:
        app: subalarm

    spec:
      containers:
      - name: subalarm

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: Always

        ports:
        - containerPort: 80